# Ketamine infusions

IV ketamine infusions will be prescribed on a paper IV Ketamine infusion chart and will require two competent registered nurses to sign for the administration (see appendix 1). 

Ketamine is also a **schedule 2 controlled drug** and will be required to be stored in the controlled drugs locked cupboard. Patients on low dose IV ketamine infusions must be cared for in either an HDU or a high observation area.

The ketamine strength used for the infusions will be 500mg/ 10ml, which will be added to 40ml of NaCl 0.9% to create a standard concentration of ketamine 10mg/ml. See appendix 2 for guidance on the preparation of the infusion. The infusion will be delivered via a locked syringe driver and the drug and line should be renewed every 24 hours.

## Starting dosages:

+	5mg/hr (0.5ml/hr) for weight ≤ 50kg - can titrated up to 10mg/hr (1.0ml/hr)

+	10mg/hr (1.0ml.hr) for weight >50kg – can be tritrated up to 20mg/hr (2.0ml/hr)

+	In the frail and elderly consider an initial dose of 0.5ml/hr with cautious dose titration.
